### ISSUE TITLE
grpc connection is unavailable

### ISSUE THREAD

**Issue by kirankt** [Akrog/cinderlib-csi#19]
Hi,
Using cinderlib/CSI with either XtremIO or RBD, I see the following issue: attach seems to work but mount fails with the following error:
MountVolume.MountDevice failed for volume "pvc-9bb7c9a98c3e11e8" : rpc error: code = Unavailable desc = grpc: the connection is unavailable

[root@kt-c7kb9 contrib]# oc get pvc
NAME      STATUS    VOLUME                 CAPACITY   ACCESS MODES   STORAGECLASS   AGE
kclaim    Bound     pvc-9bb7c9a98c3e11e8   1Gi        RWO            cinderlib      3m
[root@kt-c7kb9 contrib]# oc get all
NAME                             READY     STATUS              RESTARTS   AGE
pod/csi-cinderlib-controller-0   3/3       Running             0          4m
pod/csi-cinderlib-ds-hqm4w       2/2       Running             0          4m
pod/sleep                        0/1       ContainerCreating   0          4m

NAME                              DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/csi-cinderlib-ds   1         1         1         1            1           <none>          4m

NAME                                        DESIRED   CURRENT   AGE
statefulset.apps/csi-cinderlib-controller   1         1         4m
[root@kt-c7kb9 contrib]# 
[root@kt-c7kb9 contrib]# 
[root@kt-c7kb9 contrib]# 
[root@kt-c7kb9 contrib]# 
[root@kt-c7kb9 contrib]# oc describe pod sleep
Name:         sleep
Namespace:    csi
Node:         localhost/10.19.139.83
Start Time:   Fri, 20 Jul 2018 17:02:26 +0000
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"sleep","namespace":"csi"},"spec":{"containers":[{"args":["sleep","1000000"],"image...
              openshift.io/scc=anyuid
Status:       Pending
IP:           
Containers:
  busybox:
    Container ID:  
    Image:         busybox
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      sleep
      1000000
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /tmp/mysql from myclaim-mount (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-5krt9 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  myclaim-mount:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  kclaim
    ReadOnly:   false
  default-token-5krt9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-5krt9
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                  Age               From                     Message
  ----     ------                  ----              ----                     -------
  Normal   Scheduled               4m                default-scheduler        Successfully assigned csi/sleep to localhost
  Normal   SuccessfulAttachVolume  4m                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-9bb7c9a98c3e11e8"
  Warning  FailedMount             6s (x10 over 4m)  kubelet, localhost       MountVolume.MountDevice failed for volume "pvc-9bb7c9a98c3e11e8" : rpc error: code = Unavailable desc = grpc: the connection is unavailable
  Warning  FailedMount             6s (x2 over 2m)   kubelet, localhost       Unable to mount volumes for pod "sleep_csi(adda6e0b-8c3e-11e8-99ed-0017a4772454)": timeout expired waiting for volumes to attach or mount for pod "csi"/"sleep". list of unmounted volumes=[myclaim-mount]. list of unattached volumes=[myclaim-mount default-token-5krt9]

I also see the following in kubelet logs:

E0720 17:06:44.675459    7093 kubelet.go:1610] Unable to mount volumes for pod "sleep_csi(adda6e0b-8c3e-11e8-99ed-0017a4772454)": timeout expired waiting for volumes to attach or mount for pod "csi"/"sleep". list of unmounted volumes=[myclaim-mount]. list of unattached volumes=[myclaim-mount default-token-5krt9]; skipping pod
E0720 17:06:44.675494    7093 pod_workers.go:186] Error syncing pod adda6e0b-8c3e-11e8-99ed-0017a4772454 ("sleep_csi(adda6e0b-8c3e-11e8-99ed-0017a4772454)"), skipping: timeout expired waiting for volumes to attach or mount for pod "csi"/"sleep". list of unmounted volumes=[myclaim-mount]. list of unattached volumes=[myclaim-mount default-token-5krt9]
I0720 17:06:44.917838    7093 operation_generator.go:489] MountVolume.WaitForAttach entering for volume "pvc-9bb7c9a98c3e11e8" (UniqueName: "kubernetes.io/csi/com.redhat.cinderlib-csi^d8510041-dca7-4f10-8dd2-bf8612f1007d") pod "sleep" (UID: "adda6e0b-8c3e-11e8-99ed-0017a4772454") DevicePath "csi-bef4cd4d9c8fb774e7572baa224f885b2e3294a9f46fcdcf218c285114b8e859"
I0720 17:06:44.919864    7093 operation_generator.go:498] MountVolume.WaitForAttach succeeded for volume "pvc-9bb7c9a98c3e11e8" (UniqueName: "kubernetes.io/csi/com.redhat.cinderlib-csi^d8510041-dca7-4f10-8dd2-bf8612f1007d") pod "sleep" (UID: "adda6e0b-8c3e-11e8-99ed-0017a4772454") DevicePath "csi-bef4cd4d9c8fb774e7572baa224f885b2e3294a9f46fcdcf218c285114b8e859"
E0720 17:06:44.920299    7093 csi_attacher.go:282] kubernetes.io/csi: attacher.MountDevice failed to check STAGE_UNSTAGE_VOLUME: rpc error: code = Unavailable desc = grpc: the connection is unavailable
E0720 17:06:44.920372    7093 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/csi/com.redhat.cinderlib-csi^d8510041-dca7-4f10-8dd2-bf8612f1007d\"" failed. No retries permitted until 2018-07-20 17:08:46.920347416 +0000 UTC m=+11877.628616092 (durationBeforeRetry 2m2s). Error: "MountVolume.MountDevice failed for volume \"pvc-9bb7c9a98c3e11e8\" (UniqueName: \"kubernetes.io/csi/com.redhat.cinderlib-csi^d8510041-dca7-4f10-8dd2-bf8612f1007d\") pod \"sleep\" (UID: \"adda6e0b-8c3e-11e8-99ed-0017a4772454\") : rpc error: code = Unavailable desc = grpc: the connection is unavailable"

Any idea what might be causing this? 

Thanks
Kiran

**Comment by kirankt** [comment]
Also, I'm using OCP11:

[root@kt-c7kb9 contrib]# oc version
oc v3.11.0-alpha.0+e0f1909-460
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.11.0-alpha.0+bb11f51-481
kubernetes v1.11.0+d4cacc0

**Comment by Akrog** [comment]
This is a communication issue between _kubelet_ and the _Node_ side of the CSI plugin.  _Kubelet_ cannot establish the GRPC connection with the CSI plugin to call _NodeStageVolume_.

I can think of a couple of reasons why this can happen:
- Wrong provisioner set somewhere: Check StorageClass and the _provisioner_ parameter passed to the external provisioner.
- Wrong socket path: Check the socket path of the Node CSI plugin container or the CSI container if running a Controller+Node deployment.

**Comment by kirankt** [comment]
Hi,
Thanks for the suggestion. As you pointed out, everything looks great when the CSI_MODE is 'all'. When they are separated, I don't see any activity in the driver while using "node"  mode. Let me dig a little further to provide you more details.

**Comment by kirankt** [comment]
I've gone past this issue. On OCP, the CSI driver should host mount /var/lib/origin/openshift.local.volumes rather than /var/lib/kubelet. Interesting to note that the CSI socket directory still resides in /var/lib/kubevirt e.g. /var/lib/kubelet/plugins/com.redhat.cinderlib-csi

**Comment by Akrog** [comment]
Thank you very much for the info, and that is certainly odd, I'll have a look and see where does that difference come from.

If you are splitting the plugin into controller and node services, you may be interested in looking into the manifests I have in the new Kubernetes demo (in the `kubeyml` directory) that are splitting the services: https://github.com/Akrog/cinderlib-csi/tree/master/examples/kubernetes
